### ISSUE TITLE
Typo in Highlighted portion in screenshot below

### ISSUE THREAD

**Issue by lamyuewei** [nus-cs2113-AY1920S2/website#1]
Typo: It is up to you to get as much feedback from the ...... as you need.
Website: https://nus-cs2113-ay1920s2.github.io/website/admin/tp-supervision.html

![image](https://user-images.githubusercontent.com/60146045/80280487-f06ed300-8736-11ea-9449-ffe9168cf68e.png)

**Comment by damithc** [comment]
Thanks @lamyuewei 
Will fix in the next update.
