### ISSUE TITLE
Typo in Week 2 Topics for Repositories

### ISSUE THREAD

**Issue by lamyuewei** [nus-cs2113-AY1920S2/website#2]
Typo: "working directory" instead of "working directly"
Website: https://nus-cs2113-ay1920s2.github.io/website/schedule/week2/topics.html

Screenshot of Typo that is highlighted
![image](https://user-images.githubusercontent.com/60146045/80300450-8a825a00-87cf-11ea-84fc-ea9b59e1d19f.png)

**Comment by damithc** [comment]
Thanks for the heads up @lamyuewei 
fixed.
