### ISSUE TITLE
Examples used in Textbook UML Section

### ISSUE THREAD

**Issue by lamyuewei** [nus-cs2113-AY1920S2/website#3]
Below is the first example of a class diagram for Table with the equivalent code is given as follows:
![image](https://user-images.githubusercontent.com/60146045/80816594-5f01d400-8c02-11ea-820f-441963fd987c.png)

Next after learning about visibility, another example of the class diagram for Table is given below:
![image](https://user-images.githubusercontent.com/60146045/80816698-907a9f80-8c02-11ea-9cac-cb11890af1ef.png)
While the textbook did not say the Table class is still the same code, it might be misleading to the students as the weaker student might mistakenly think that default attributes is (-) visibility and default methods is (+) visibility instead of (~) visibility if they still refer to the same set of codes above.

Perhaps, it might be better to change the existing code in the first picture OR to simply just add another equivalent code for the second picture with the property and methods matching the right visibility.

Just a suggestion, feel free to ignore this issue if it is not deem an issue.

**Comment by damithc** [comment]
Good point @lamyuewei 
Will update in the next semester's version.

**Comment by damithc** [comment]
Updated in the next semester's version.
